proxy:
  '/parodos':
    target: 'http://localhost:8080/api/v1'
    changeOrigin: true
    redirect: follow
    cache: 'no-cache'
    allowedHeaders:
      - Authorization
    headers:
      Content-Type: 'application/json'
      accept: 'application/json'

  '/parodos-notifications':
    target: 'http://localhost:8081/api/v1'
    changeOrigin: true
    redirect: follow
    cache: 'no-cache'
    allowedHeaders:
      - Authorization
    headers:
      Content-Type: 'application/json'
      accept: 'application/json'
